# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#0077FF>Reforged Eden 1.10</color></b> <size=65%><#ffffff>(build 49)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>June 27:</b></color></size>
  <size=85%>•<indent=3%>Added new blocks, items, and NPCs from the Empyrion 1.10 game update.</indent>
  <indent=3%><i>Drone bay is currently not available for crafting or saving in blueprints. It can be obtained via the item menu for testing in survival.</i></indent>
  •<indent=3%>Updated game options file included with scenario. Mass and volume enabled by default. (can disable in difficulty menu)</indent>
  •<indent=3%>Increased HV and SV mechanical drill max count from 8 to 10.</indent>
  •<indent=3%>Fixed hacker and courier class not being activatible.</indent>
  •<indent=3%>Misc fixes.</indent>
  •<indent=3%>Added vanilla prefabs from 1.09 to prevent POI spawn issues in 1.10.</indent></size>
  
  <#ffff00>It's recommended to back up your save games and blueprints due to the Empyrion 1.10 game update.</color>
  <#ffff00>If you got yourself stuck on a motorbike, see the change notes on the workshop for a fix.</color>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p05

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 15

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
ShowTimes:
  # p05: 6
  # p06: 8
