# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#0077FF>Reforged Eden</color></b> <size=65%><#ffffff>(build 85)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>March 28:</b></color></size>
  <size=85%>•<indent=3%>Added new CV/BA and HV/SV Gravity Generators.</indent></size>
  <size=85%>•<indent=3%>Fixed incorrect coordinates on Object 82 mission dialogue.</indent></size>
  <size=85%>•<indent=3%>Increased quantities of optronics and robotics that advanced factories buy.</indent></size>
  <size=85%>•<indent=3%>Updated donation info in the Reforged Galaxy section of the Empyriopedia to fix broken donation links.</indent></size>
  
  <size=85%><#ffffff>Reforged Eden does not require or contain content from the Dark Faction DLC. Owning Dark Faction will have no impact on Reforged Eden.</color></size>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p49

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 15

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
# ShowTimes:
  # p49: 45
  # p06: 8
